data:
  raw:
    new: data/raw/new.csv
    test: data/raw/test.csv
    combined: data/raw/pet.csv
  processed: data/processed/
  validation: data/validation/
  final: data/final/

report: 
  data_integrity: report/data_integrity.html
  train_test_validation: report/train_test_validation.html
  model_evaluation: report/model_evaluation.html
  full_suite: report/full_suite.html

connection:
  user: postgres
  password: 123456
  host: localhost:5432
  database: pet_finder

n_estimators: 20
check_integrity_cols:
  - Type
  - Age
  - Breed1
  - Breed2
  - Gender
  - Color1
  - Color2
  - Color3
  - MaturitySize
  - FurLength
  - Vaccinated
  - Dewormed
  - Sterilized
  - Health
  - Quantity
  - Fee
  - AdoptionSpeed
use_cols:
  - Type
  - Age
  - Breed1
  - Breed2
  - Gender
  - Color1
  - Color2
  - Color3
  - MaturitySize
  - FurLength
  - Vaccinated
  - Dewormed
  - Sterilized
  - Health
  - Quantity
  - Fee
  - desc_length
  - desc_words
  - average_word_length
  - AdoptionSpeed
cat_cols:
  - Type
  - Breed1
  - Breed2
  - Gender
  - Color1
  - Color2
  - Color3
  - MaturitySize
  - FurLength
  - Vaccinated
  - Dewormed
  - Sterilized
  - Health
label: AdoptionSpeed

n_splits: 5
params:
  objective: multiclass
  max_depth: 4
  alpha: 10
  learning_rate: 1.0
  n_estimators: 10
  random_state: 0

model:
  save_path: model/xgboost
