defaults:
  - data: data
  - _self_

n_estimators: 20
use_cols:
  - Type
  - Age
  - Breed1
  - Breed2
  - Gender 
  - Color1
  - Color2
  - Color3
  - MaturitySize
  - FurLength
  - Vaccinated
  - Dewormed
  - Sterilized
  - Health
  - Quantity
  - Fee
  - desc_length
  - desc_words
  - average_word_length
  - AdoptionSpeed
cat_cols:
  - Type
  - Breed1
  - Breed2
  - Gender
  - Color1
  - Color2
  - Color3
  - MaturitySize
  - FurLength
  - Vaccinated
  - Dewormed
  - Sterilized
  - Health
