name: Deploy flow
on:
  push:
    paths:
      - config/**
      - src/**
      - .github/workflows/test_training.yaml
jobs:
  deploy_prefect:
    name: Deploy flows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
        
      - name: Install packages
        run: pip install -r requirements.txt

      - name: Login to Prefect Cloud 2.0
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        run: prefect cloud login --key $PREFECT_API_KEY --workspace <my-workspace>